import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { usePageData } from '../components/data-atom'
export default function Home(props: any) {
  const breeds = usePageData('breeds.data', '');
  const link = usePageData('breeds.links.self', '');
  console.log('breeds', breeds);
  const names = breeds.map((breed: any) => breed.attributes.name);

  return (
    <div className={styles.container}>
      <Head>
        <title>with-jotai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>Testing...</h1>
      <main className={styles.main}>
        {names}
        <br/>
        {link}
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const response = await fetch("https://dogapi.dog/api/v2/breeds");
  const breeds = await response.json();
  return {
    props: {
      breeds
    }
  }
}